repos:
- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.13
  hooks:
  - id: mdformat
    additional_dependencies:
    - mdformat-beautysh
    - mdformat-black
    - black==22.1.0
    - mdformat-config
    - mdformat-gfm
    - mdformat-web
- repo: https://github.com/lovesegfault/beautysh
  rev: v6.2.1
  hooks:
  - id: beautysh
- repo: https://github.com/psf/black
  rev: 22.1.0
  hooks:
  - id: black
