# AllWISE xmatch
steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/ardent-cycling-243415/ztf-xmatch_allwise-allwise', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/ardent-cycling-243415/ztf-xmatch_allwise-allwise']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'xmatch-AllWISE', '--image', 'gcr.io/ardent-cycling-243415/ztf-xmatch_allwise-allwise', '--region', 'us-central1']
images:
- gcr.io/ardent-cycling-243415/ztf-xmatch_allwise-allwise
