# Creates a Compute Engine instance template for the
# Consumer VM (with the Kafka -> Pub/Sub connector)
---
steps:
# 0. Build the container image from the Dockerfile in this directory
- name: "gcr.io/cloud-builders/docker"
  args:
  - "build"
  - "-t"
  - "gcr.io/${PROJECT_ID}/${_IMAGE_NAME}"
  - "."
# 1. Push the image to the Container Registry
- name: "gcr.io/cloud-builders/docker"
  args:
  - "push"
  - "gcr.io/${PROJECT_ID}/${_IMAGE_NAME}"
# 2. Create an instance template from the container
- name: "gcr.io/cloud-builders/gcloud"
  args:
  - "compute"
  - "instance-templates"
  - "create-with-container"
  - "${_INSTANCE_TEMPLATE_NAME}"
  - "--container-image=gcr.io/${PROJECT_ID}/${_IMAGE_NAME}"
  - "--machine-type=g1-small"
  - "--scopes=cloud-platform"
  - "--tags=ztfport"
  - "--image=projects/cos-cloud/global/images/cos-stable-93-16623-39-30"
  - "--boot-disk-size=10GB"
  - "--boot-disk-device-name=persistent-disk-0"
substitutions:
    _IMAGE_NAME: "kafka_pubsub_connector"
    _INSTANCE_TEMPLATE_NAME: "kafka-pubsub-connector"
