# --------------- References ------------------ #
# Cloud Build Overview: https://cloud.google.com/build/docs/overview
# Deploying to Cloud Run: https://cloud.google.com/build/docs/deploying-builds/deploy-cloud-run
# Schema for this file: https://cloud.google.com/build/docs/build-config-file-schema
#
# --------------- Substitutions --------------- #
substitutions:
  _IMAGE_NAME: 'gcr.io/${PROJECT_ID}/${_REPOSITORY}/${_MODULE_NAME}'
  _IMAGE_PATH: '${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}'
  # Different GCP services use different names for the same env variable:
  # PROJECT_ID, GOOGLE_CLOUD_PROJECT, and GCP_PROJECT.
  # We will use GCP_PROJECT as the env variable of our deployed Cloud Run service
  # for consistency with Cloud Functions, which sets this variable automatically.
  _MODULE_ENV: 'GCP_PROJECT=${PROJECT_ID},SURVEY=${_SURVEY},TESTID=${_TESTID}'
#
# --------------- Steps ----------------------- #
steps:
# Ancillaries: Create ancillary resources.
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: Ancillaries
  waitFor: ['-']
  entrypoint: bash
  args:
    - '-c'
    # Here we are just copying the needed files from the local machine.
    # For automatic deployments from GitHub, clone the repo instead.
    - |
      cp create-ancillaries.sh construct-name.sh /workspace/
      chmod +x /workspace/create-ancillaries.sh /workspace/construct-name.sh
      /workspace/create-ancillaries.sh
# Build: Build the image.
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  waitFor: ['-']
  args: ['build', '-t', '${_IMAGE_PATH}', '.']
# Push: Push the image to the repository.
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  waitFor: ['Build']
  args: ['push', '${_IMAGE_PATH}']
# Deploy: Deploy the Cloud Run service.
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: Deploy
  waitFor: ['Push']  # [CHECKME] Does this also need to wait for Ancillaries?
  entrypoint: gcloud
  args: ['run', 'deploy', '${_MODULE_NAME}', '--image', '${_IMAGE_PATH}', '--region', '${LOCATION}', '--set-env-vars', '${_MODULE_ENV}']
#
# --------------- Other ----------------------- #
images:
- '${_IMAGE_PATH}'
options:
  # Include all built-in and custom substitutions as env variables for all build steps.
  automapSubstitutions: true
  # Within user-defined substitutions, allow referencing of other variables and bash parameter expansion.
  # https://cloud.google.com/build/docs/configuring-builds/use-bash-and-bindings-in-substitutions#bash_parameter_expansions
  dynamic_substitutions: true
