name: Reusable workflow example

on:
  workflow_call:
    inputs:
      parent_directory:
        required: true
        type: string

    outputs:
      microservices:
        description: "An array of subdirectories representing microservices."
        value: ${{ jobs.discover_services.outputs.microservices }}

jobs:
  discover_services: # Identify any microservices that have an associated test suite
    name: Discover Microservices
    runs-on: ubuntu-latest

    outputs:
      microservices: ${{ steps.create-output-matrix.outputs.service_list }}

    steps:
      - uses: actions/checkout@v2
        name: Checkout repositotory

      - id: create-output-matrix
        name: Create list of microservices
        run: echo "::set-output name=service_list::$(ls|jq -cnR '[inputs | select(length>0)]')"
