name: Reusable workflow example

on:
  workflow_call:
    inputs:
      parent_directory:
        required: true
        type: string

    outputs:
      microservices:
        description: "An array of subdirectories representing microservices."
        value: ${{ jobs.find_services.outputs.microservices }}

jobs:
  find_services:
    name: Discover Microservices
    runs-on: ubuntu-latest
    outputs:
      microservices: ${{ steps.create-output-matrix.outputs.service_list }}

    steps:
      - uses: actions/checkout@v2
        name: Checkout repositotory

      - id: create-output-matrix
        name: Create list of microservices
        run: |
          
          testvar="['a','b']"
          subdirectoriesx=$(
              echo -n '['
              for FILE in $(ls ${{ inputs.parent_directory }}/* -d | sed -e 's/"/\\"/g'); do
                echo -n \"${FILE}\",
              done
              echo -en \\b']'
          
            )
          
          echo $testvar
          echo $subdirectories
          echo "::set-output name=service_list::$testvar"
