name: Test Cloud Functions

on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - '**:**'  # Only run for pull requests submitted from forks

jobs:
  find_services:
    name: Discover Microservices
    uses: ./.github/workflows/FindMicroservices.yml
    with:
      parent_directory: "broker/cloud_functions"

  run_tests: # Run the tests for each service
    name: Execute Test Suite
    needs: find_services
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service_directory: ${{ fromJson(needs.find_services.outputs.microservices) }}

    defaults:
      run:
        working-directory: ${{ matrix.service_directory }}

    steps:
      - uses: actions/checkout@v2
        name: Checkout repository

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Install coverage tool
        run: pip install coverage

      - name: Run tests with coverage
        run: |
          coverage run -m unittest
          coverage xml -o report_${{ matrix.python }}.xml
          coverage report

      - name: Archive coverage results
        uses: actions/upload-artifact@v3
        with:
          path: report_${{ matrix.python }}.xml

      # Report test coverage to codacy for the current set of tests
      - name: Report partial coverage results
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report --partial -l Python -r report_${{ matrix.python-version }}.xml
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}