name: Run Tests

on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - '**:**'  # Only run for pull requests submitted from forks

jobs:
  find_services: # Identify any microservices that have an associated test suite
    name: Discover Microservices
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout repositotory

      - id: create-output-matrix
        name: Create list of microservices
        run: |
          
          echo "::set-output name=service_list::[$(ls -dm broker/cloud_functions/*)]"

    outputs:
      microservices: ${{ steps.create-output-matrix.outputs.service_list }}

  run_tests: # Run the tests for each service
    name: Execute Test Suite
    needs: find_services
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: ${{ needs.find_services.outputs.microservices }}

    steps:
      - uses: actions/checkout@v2
        name: Checkout repositotory
      - run: ls -dm broker/cloud_functions/*
      - run: echo ${{ matrix.service }}