name: Test Cloud Functions

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  run_tests: 
    name: Test Service
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.8", "3.9", "3.10", "3.11" ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install requirements
        run: |
          if [ -f "requirements.txt" ]; 
          then
            pip install -r requirements.txt
          else:
            echo "No requirements file found."
          fi
      - name: Install coverage tool
        run: pip install coverage

      - name: Run tests with coverage
        run: |
          coverage run -m unittest
          coverage xml -o report_${{ matrix.python-version }}.xml
          coverage report
      - name: Archive coverage results
        uses: actions/upload-artifact@v3
        with:
          path: report_${{ matrix.python-version }}.xml

      # Report test coverage to codacy for the current set of tests
      - name: Report partial coverage results
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report --partial -l Python -r report_${{ matrix.python-version }}.xml
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}