name: Run Unit Tests

on:
  push:
  pull_request:
    branches:
      - '**:**'  # Only run for pull requests submitted from forks

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  python_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.7, 3.8, 3.9 ]

    steps:
      - name: Checkout source
        uses: actions/checkout@master

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install test dependencies
        run: |
          pip install coverage

      - name: Run tests with coverage
        run: |
          coverage run -m unittest
          coverage report
