name: Run Tests

on: 
  workflow_dispatch:

jobs:
  find_services:  # Identify any microservices that have an associated test suite
    name: Find Testable Services 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout repositotory 
        
      - id: set-matrix
        name: Create list of microservices
        run: echo "::set-output name=service_list::['a', 'b']"

    outputs:
        service_list: ${{ steps.set-matrix.outputs.service_list }}
    
  run_tests:  # Run the tests for each service
    name: Execute Test Suite
    needs: find_services
    runs-on: ubuntu-latest

    strategy:
      matrix:
        container: ${{ fromJson(needs.find_services.outputs.service_list) }}

    container:
      image: ${{ matrix.container }}

    steps:
      - name: Install test dependencies
        run: |
          pip install coverage

      - name: Run tests with coverage
        run: |
          coverage run -m unittest
          coverage xml -o report_${{ matrix.python }}.xml
          coverage report
          
      - name: Archive coverage results
        uses: actions/upload-artifact@v3
        with:
          path: report_${{ matrix.python }}.xml
          
      # Report test coverage to codacy for the current set of tests
      - name: Report partial coverage results
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report --partial -l Python -r report_${{ matrix.python-version }}.xml
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

  codacy-coverage-reporter:  # Tell codacy we are done reporting test coverage
    name: Report code coverage
    runs-on: ubuntu-latest
    needs: run_tests
    steps:
      - name: Finish reporting coverage
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) final
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
